version: '3'
services:
  neurawebapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

networks:
  default:
    external: true
    name: neuranet